(add-to-list 'load-path "~/.emacs.d/site-lisp/anything-config")
(require 'anything-config)
(require 'anything-elscreen)
(global-set-key (kbd "<f5> s") 'anything-elscreen-complete)
(global-set-key (kbd "C-z") 'anything)
(global-set-key (kbd "<f5> k") 'anything-show-kill-ring)
(global-set-key (kbd "<f5> m") 'anything-all-mark-rings)
(global-set-key (kbd "<f5> c") 'anything-browse-code)
(provide 'init-anything)
