(add-to-list 'load-path "~/.emacs.d/site-lisp/color-theme/")
(require 'color-theme)
(color-theme-initialize)
(setq color-theme-load-all-themes nil)
(require 'color-theme)
(require 'color-theme-tangotango)
;(require 'color-theme-sons-of-obsidian)
;(color-theme-sons-of-obsidian)
(color-theme-tangotango)
(provide 'init-color-theme)
