; file   turbonium.el
; author Windsor Schmidt <windsor.schmidt@gmail.com>
; date   Sun, Feb 20 2011
;
; Turbonium color theme for emacs (tested with emacs23 on Debian x86-32).
; Based on Blue Mood color theme by Nelson Loyola.

(defun color-theme-turbonium ()
  "Turbonium theme. Based on Blue Mood color theme by Nelson Loyola."
  (interactive)
  (color-theme-install
   '(color-theme-turbonium
     ((background-color . "#0e0e0e")
      (background-mode . dark)
      (background-toolbar-color . "#121212")
      (border-color . "#000000")
      (border-color . "#000000000000")
      (bottom-toolbar-shadow-color . "#6c6c68686868")
      (cursor-color . "DarkGoldenrod1")
      (foreground-color . "#a0a0a0")
      (mouse-color . "black")
      (top-toolbar-shadow-color . "#e5e5e0e0e1e1"))
     ((vc-annotate-very-old-color . "#0046FF"))
     (default ((t (nil))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (nil))))
     (border-glyph ((t (nil))))
     (cmode-bracket-face ((t (:bold t))))
     (cperl-array-face ((t (:bold t :foreground "red"))))
     (cperl-hash-face ((t (:bold t :foreground "chartreuse"))))
     (custom-button-face ((t (nil))))
     (custom-changed-face ((t (:background "blue" :foreground "red"))))
     (custom-documentation-face ((t (nil))))
     (custom-face-tag-face ((t (:underline t))))
     (custom-group-tag-face ((t (:underline t :foreground "blue"))))
     (custom-group-tag-face-1 ((t (:underline t :foreground "red"))))
     (custom-invalid-face ((t (:background "#404040" :foreground "yellow"))))
     (custom-modified-face ((t (:background "blue" :foreground "red"))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-saved-face ((t (:underline t))))
     (custom-set-face ((t (:background "red" :foreground "blue"))))
     (custom-state-face ((t (:bold t :foreground "cyan"))))
     (custom-variable-button-face ((t (:underline t :bold t))))
     (custom-variable-tag-face ((t (:underline t :foreground "blue"))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue"))))
     (font-lock-builtin-face ((t (:bold t :foreground "#2266ee"))))
     (font-lock-comment-face ((t (:bold t :foreground "#89dd12"))))
     (font-lock-constant-face ((t (:bold t :foreground "#2266ee"))))
     (font-lock-doc-string-face ((t (:foreground "#00C000"))))
     (font-lock-function-name-face ((t (:bold t :foreground "#3066ee"))))
     (font-lock-keyword-face ((t (:bold t :foreground "d0d000"))))
     (font-lock-other-emphasized-face ((t (:bold t :foreground "purple"))))
     (font-lock-other-type-face ((t (:bold t :foreground "purple"))))
     (font-lock-preprocessor-face ((t (:foreground "#9060f0"))))
     (font-lock-reference-face ((t (:bold t :foreground "orangered"))))
     (font-lock-string-face ((t (:foreground "#fa9300"))))
     (font-lock-type-face ((t (:bold t :foreground "gold1"))))
     (font-lock-variable-name-face ((t (:foreground "2266ee"))))
     (font-lock-warning-face ((t (:foreground "tomato"))))
     (green ((t (:foreground "#89dd12"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:size "nil" :background "#e7e3d6" :foreground" #000000"))))
     (highlight ((t (:background "404040" :foreground "#e0e0e0"))))
     (isearch ((t (:bold t :background "pale turquoise" :foreground "blue"))))
     (italic ((t (nil))))
     (lazy-highlight-face ((t (:bold t :foreground "dark magenta"))))
     (left-margin ((t (nil))))
     (list-mode-item-selected ((t (:bold t :background "gray68" :foreground "yellow"))))
     (modeline ((t (:background "#000000" :foreground "#d0d0d0"))))
     (modeline-buffer-id ((t (:background "#000000" :foreground "d0d0d0"))))
     (modeline-mousable ((t (:background "goldenrod" :foreground "darkblue"))))
     (modeline-mousable-minor-mode ((t (:background "goldenrod" :foreground "darkblue"))))
     (my-tab-face ((t (:background "SlateBlue1"))))
     (p4-depot-added-face ((t (:foreground "steelblue1"))))
     (p4-depot-deleted-face ((t (:foreground "red"))))
     (p4-depot-unmapped-face ((t (:foreground "grey90"))))
     (p4-diff-change-face ((t (:foreground "#89dd12"))))
     (p4-diff-del-face ((t (:bold t :foreground "salmon"))))
     (p4-diff-file-face ((t (:background "blue"))))
     (p4-diff-head-face ((t (:background "blue"))))
     (p4-diff-ins-face ((t (:foreground "steelblue1"))))
     (paren-blink-off ((t (:foreground "DodgerBlue4"))))
     (paren-match ((t (:background "#89dd12" :foreground "white"))))
     (paren-mismatch ((t (:background "DeepPink"))))
     (pointer ((t (:background "red"))))
     (primary-selection ((t (:bold t :background "medium sea #89dd12"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "#303030" :foreground "#e0e0e0"))))
     (right-margin ((t (nil))))
     (secondary-selection ((t (:background "gray91" :foreground "sienna3"))))
     (show-paren-match-face ((t (:background "cyan3" :foreground "blue"))))
     (show-paren-mismatch-face ((t (:background "red" :foreground "blue"))))
     (show-trailing-whitespace ((t (:background "red" :foreground "blue"))))
     (speedbar-button-face ((t (:foreground "white"))))
     (speedbar-directory-face ((t (:foreground "gray"))))
     (speedbar-file-face ((t (:foreground "gold1"))))
     (speedbar-highlight-face ((t (:background "lightslateblue" :foreground "gold1"))))
     (speedbar-selected-face ((t (:underline t :foreground "red"))))
     (speedbar-tag-face ((t (:foreground "chartreuse"))))
     (text-cursor ((t (:background "DarkGoldenrod1" :foreground "DodgerBlue4"))))
     (toolbar ((t (:background "#e7e3d6" :foreground "#000000"))))
     (underline ((t (:underline t))))
     (vertical-divider ((t (:background "#e7e3d6" :foreground "#000000"))))
     (widget-button-face ((t (:bold t))))
     (widget-button-pressed-face ((t (:foreground "red"))))
     (widget-documentation-face ((t (:foreground "#89dd12"))))
     (widget-field-face ((t (:background "gray85"))))
     (widget-inactive-face ((t (:foreground "dim gray"))))
     (widget-single-line-field-face ((t (:background "gray85"))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "white" :foreground "midnightblue")))))))
(provide 'color-theme-turbonium)
(add-to-list 'color-themes '(color-theme-turbonium  "Turbonium" "Windsor Schmidt (based on Blue Mood)"))
